# Generated by Django 2.0.3 on 2018-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pic',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
