# Generated by Django 2.0.3 on 2018-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellparts', '0002_auto_20180524_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pic',
            field=models.ImageField(upload_to='parts/', verbose_name='Картинка'),
        ),
    ]
