# Generated by Django 2.0.5 on 2018-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180524_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
        migrations.AddField(
            model_name='service',
            name='cost_1',
            field=models.FloatField(null=True, verbose_name='Легковые (A, B, C)'),
        ),
        migrations.AddField(
            model_name='service',
            name='cost_2',
            field=models.FloatField(null=True, verbose_name='Легковые (D, E, F)'),
        ),
        migrations.AddField(
            model_name='service',
            name='cost_3',
            field=models.FloatField(null=True, verbose_name='Джипы и минивены'),
        ),
    ]
