# Generated by Django 2.0.3 on 2018-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180702_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
