# Generated by Django 2.0.5 on 2018-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180702_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost_1',
            field=models.IntegerField(null=True, verbose_name='Легковые (A, B, C)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_2',
            field=models.IntegerField(null=True, verbose_name='Легковые (D, E, F)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_3',
            field=models.IntegerField(null=True, verbose_name='Джипы и минивены'),
        ),
    ]
