# Generated by Django 2.0.5 on 2018-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180702_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost_1',
            field=models.CharField(max_length=10, null=True, verbose_name='Легковые (A, B, C)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_2',
            field=models.CharField(max_length=10, null=True, verbose_name='Легковые (D, E, F)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_3',
            field=models.CharField(max_length=10, null=True, verbose_name='Джипы и минивены'),
        ),
    ]
