# Generated by Django 2.0.3 on 2018-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер заказа'),
        ),
    ]
