# Generated by Django 2.0.3 on 2018-07-02 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20180702_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 2, 9, 42, 54, 107335), verbose_name='Дата заказа'),
        ),
    ]
