# Generated by Django 2.0.5 on 2018-07-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20180702_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=40, verbose_name='ФИО Заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='problem',
            field=models.TextField(null=True, verbose_name='Коротко опишите проблему'),
        ),
    ]
